# joint_limits.yaml는 URDF의 동역학 속성을 덮어쓰거나 보완한다.
default_velocity_scaling_factor: 0.2
default_acceleration_scaling_factor: 0.2

joint_limits:
  arm_shoulder_pan:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 2.0
  arm_shoulder_lift:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 2.0
  arm_elbow_flex:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 2.0
  arm_wrist_flex:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 2.0
  arm_wrist_roll:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 2.0
  arm_gripper:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: false
    max_acceleration: 0
