[Service]
Environment=ROS_DOMAIN_ID=12
Environment=ROS_AUTOMATIC_DISCOVERY_RANGE=SUBNET
Environment=FASTDDS_BUILTIN_TRANSPORTS=UDPv4
ExecStart=
ExecStart=/bin/bash -c "source /opt/ros/jazzy/setup.bash && source /home/lim/jdamr_ws/install/setup.bash && exec ros2 launch jdamr_cube_bringup real_bringup.launch.py wheel_radius:=0.0329 wheel_separation:=0.510"
